### ISSUE TITLE
Is this the best way to switch between orgmode and program mode for editing code

### ISSUE THREAD

**Issue by 00krishna** [alphapapa/outorg#2]
Hello Professor. 

I posted this question on [reddit](https://www.reddit.com/r/emacs/comments/7sxyfa/literate_programming_best_practices_flpping/) too thought you might have some insights--since you have written so much on literate programming with org-mode, etc. 

> 
> I am trying to find a good workflow to manage this problem. So I use orgmode for a lot of my project management, etc. I want to start using more of the literate programming features, where I can write code in source blocks and then tangle them to generate source files. I was wondering what other folks do to flip back and forth between the programming phase of literate programming versus the literate phase.
> 
> Let me layout a simple scenario and then identify some tools that I have found. So if I start a new project, I generally want to perhaps plan my classes and modules--so I would use the literate part of literate programming to create an orgmode file with perhaps some graphviz class diagrams, etc. I might use a mix of languages such as some python and cython or perhaps some rust or golang nowadays.
> 
> Then I would start to code the classes. Of course that is a very programming intensive step and I want to use tools like code completion and linting, and syntax coloring etc., to help write the code.
> 
> But then I want to switch back to the literate phase where I can write out some profiling code and document the results.
> 
> I have seen a package called outorg maintained by alphapapa that should help with this. There is also a package lentic. I don't have any experience with these packages, but was hoping someone might indicate their workflow and also the tools they use to deal with the problem above--whether those tools be the ones I identified or any others.

The question is really about workflow for literate versus programming phases of writing code. Right now I generally just start by writing the code in the emacs major mode and trying to get it working. Then once it works I basically copy it over to the orgmode file and set it up for tangling. Sometimes I just create one big code block in the orgmode file and get it working, and then break it up. These work, but I was hoping for something a little less manual, haha. I was just wondering what your workflow was to deal with this challenge? Since you maintain `outorg` and `outshine` I thought you might have an opinion on those as solutions.

**Comment by alphapapa** [comment]
> Hello Professor.

I'm not a professor, but hi.  :)

> I posted this question on reddit too thought you might have some insights

I posted a reply there so others can read it too.

> --since you have written so much on literate programming with org-mode, etc.

I haven't really, so I wonder if you have confused me with someone else.  :)

>  Right now I generally just start by writing the code in the emacs major mode and trying to get it working. Then once it works I basically copy it over to the orgmode file and set it up for tangling. Sometimes I just create one big code block in the orgmode file and get it working, and then break it up. These work, but I was hoping for something a little less manual, haha.

Well, frankly, I would challenge the idea of using Org and tangling in the first place.  What are the problems you're trying to solve by doing so?  As you noted, it requires some manual effort.  What are the benefits, and do they outweigh the drawbacks?  In most cases, I don't think they do, and you can get most of the benefits of Org commenting and task management by using something like `outorg` or `lentic`, while preserving the code as intact code files rather than Org files which require tangling.

You mentioned using Org for profiling and documentation: it's very useful for that, indeed, but it doesn't require that the code being profiled be in the Org file itself.  You can use an Org source block to run a profiling script that runs the actual program.  This also separates code from data and documentation, which is generally a good idea.

Well, I hope these comments and the Reddit reply help answer your questions.  Let me know if you have any other thoughts!

**Comment by 00krishna** [comment]
Ahh okay. Sorry I totally was thinking you were John Kitchn. My mistake. 

I read your comments on reddit and will respond there. I think this is a really interesting conversation, since there is a very particular use case I am working on that is probably very generalizable. I will close out this issue and continue the conversation on reddit. Thanks for responding to this issue so quickly.

**Comment by alphapapa** [comment]
> Ahh okay. Sorry I totally was thinking you were John Kitchn. My mistake.

Hey, I don't mind being confused with him, he's awesome.  :D
